0x08. Networking basics #1

diff --git a/0x08-networking_basics_2/0-change_your_home_IP b/0x08-networking_basics_2/0-change_your_home_IP
--- a/0x08-networking_basics_2/0-change_your_home_IP
+++ b/0x08-networking_basics_2/0-change_your_home_IP
@@ -1,10 +1,21 @@
 #!/usr/bin/env bash
-# configures an Ubuntu server to: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
+#
+# Configure resolution of localhost to 127.0.0.2 and facebook.com to 8.8.8.8
 
-cp /etc/hosts ~/hosts.new
+if (( ${UID:-$(id -u)} ))
+then
+	echo 'Must be run as root'
+	exit 1
+fi
 
-echo "127.0.0.2		localhost" > ~/hosts.new
+if ! tempfile="$(mktemp)"
+then
+	echo 'Unable to create temporary file'
+	exit 1
+fi
+{ printf '%s\t%s\n' 127.0.0.2 localhost
+	printf '%s\t%s\n' 8.8.8.8   facebook.com
+	cat /etc/hosts
+} > "${tempfile}"
 
-echo "8.8.8.8		facebook.com" >> ~/hosts.new
-
-cp -f ~/hosts.new /etc/hosts
+cat -- "${tempfile}" > /etc/hosts
